### ISSUE TITLE
Sticky ScrollView not working after build with Progaurd

### ISSUE THREAD

**Issue by venkatsaravanan** [emilsjolander/StickyScrollViewItems#15]
Hello,
    StickyScrollview working fine when run on devices, but it not working when i generate a build with progaurd. please give some solution 
note: i also tired this below one
-keep class com.emilsjolander.*\* { _; } -dontwarn com.emilsjolander._*

**Comment by parkin** [comment]
What do you mean by not working?

Also, I've used the library successfully with Proguard without doing anything special. so it's possible.

**Comment by emilsjolander** [comment]
if you tell progaurd to ignore at of the classes within StickyScrollViewItems you really should not have any problems. It should work without ignoring to though. My guess is that something is wrong in your configuration as it works fine for others

**Comment by venkatsaravanan** [comment]
Thanks for your mail, now it's working
