### ISSUE TITLE
Can't import in Android Studio

### ISSUE THREAD

**Issue by deckyfx** [emilsjolander/StickyScrollViewItems#8]
When try to import using android studio 0.3.1

Got this error
No such property: SONATYPE_USERNAME for class: org.gradle.api.publication.maven.internal.ant.DefaultGroovyMavenDeployer

**Comment by emilsjolander** [comment]
I recently imported it with the same android studio version and didn't have any problems. Did you manage to fix it?

**Comment by deckyfx** [comment]
Yes, i ise the newest version and now the problem is solved, thanks

**Comment by mrtristan** [comment]
i just NOW downloaded android studio and got this issue. i can only assume that i'm running the latest version...

**Comment by deckyfx** [comment]
in your build.gradle project put this (not top build.gradle)

dependencies {
    ...
    compile 'se.emilsjolander:StickyScrollViewItems:1.0.0@aar'
}

**Comment by h777arsh** [comment]
ok thanks it did help :D

**Comment by Hit0** [comment]
I have the latest android studio version and make the same mistake of 1412
